### ISSUE TITLE
Does this library work with API v5.9?

### ISSUE THREAD

**Issue by bixelsnl** [joost/transip#11]
I have the need to talk to the TransIP api from a Ruby application. To prevent re-inventing the wheel I am having a look if there are any existing libraries. This seems to be the only one, but it's been a while since there have been any code changes and the README mentions only compatibility with API V5.0.

Can you say whether this library also works with API v5.9 ?

**Comment by richmans** [comment]
Hi!

I have a script running on my server that tests a set_dns_entries call every day. So i know that works, but i haven't tested any other features of the api.

Richard

**Comment by bixelsnl** [comment]
Roger, thanks !

**Comment by joost** [comment]
Updated some docs to show some activity.
